# Generated by Django 4.1.7 on 2023-03-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="last_name",
            field=models.CharField(default="1", max_length=100),
            preserve_default=False,
        ),
    ]
